### ISSUE TITLE
this.items not updating in performClick()

### ISSUE THREAD

**Issue by jssisodiya** [pratikbutani/MultiSelectSpinner#1]
After setting items from parameters to this.items in MultiSpinner, I am not able to access updated items' value and thus it throws an Null pointer exception.
**java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference**

If I declare the member variables of class Multi Spinner as static, it works fine. 
Can you tell me what is happening wrong here?

Thanks in advance.

**Comment by pratikbutani** [comment]
@jssisodiya  Can you post your edited code, what you have done?

**Comment by jssisodiya** [comment]
In onCreateView of myFragment.java, I am calling MultiSpinner object.
`final View rootView = inflater.inflate(R.layout.fragment_create_entity, container, false);

        final List<String> list= new ArrayList<String>();
        list.add("item 1");
        list.add("Item 2");
        list.add("item 3");
        list.add("item 4");

        Log.v("size of list", " : "+list.size());
        MultiSpinner simpleSpinner = (MultiSpinner) rootView.findViewById(R.id.simpleMultiSpinner);

        simpleSpinner.setItems(list, "Select something..", -1, new MultiSpinner.MultiSpinnerListener() {

            @Override
            public void onItemsSelected(boolean[] selected) {

                Log.v("onItemSelected", ":: ");
                // your operation with code...
                for(int i=0; i<selected.length; i++) {
                    if(selected[i]) {
                        Log.i("TAG", i + " : "+ list.get(i));
                    }
                }
            }
        });`

I haven't changed anything in MultiSpinner class. Still pasting the MultiSpinner.java contents below. There might be few log statements for debugging. I checked the value of List sent as parameters in setItems. Its fine, but when performClick is called, its not able to access the value being set in setItems.
`public class MultiSpinner extends Spinner implements OnMultiChoiceClickListener, OnCancelListener {

    private List<String> items;
    private boolean[] selected;
    private String defaultText;
    private MultiSpinnerListener listener;

    public MultiSpinner(Context context) {
        super(context);
    }

    public MultiSpinner(Context arg0, AttributeSet arg1) {
        super(arg0, arg1);
    }

    public MultiSpinner(Context arg0, AttributeSet arg1, int arg2) {
        super(arg0, arg1, arg2);
    }

    @Override
    public void onClick(DialogInterface dialog, int which, boolean isChecked) {
        if (isChecked)
            selected[which] = true;
        else
            selected[which] = false;
    }

    @Override
    public void onCancel(DialogInterface dialog) {
        // refresh text on spinner
        Log.v("onCancel", "in onCancel");
        StringBuffer spinnerBuffer = new StringBuffer();

        for (int i = 0; i < items.size(); i++) {
            if (selected[i] == true) {
                spinnerBuffer.append(items.get(i));
                spinnerBuffer.append(", ");
            }
        }

        String spinnerText = "";
        spinnerText = spinnerBuffer.toString();
        if (spinnerText.length() > 2)
            spinnerText = spinnerText.substring(0, spinnerText.length() - 2);
        else
            spinnerText = defaultText;

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getContext(),
                R.layout.textview_for_spinner,
                new String[] { spinnerText });
        setAdapter(adapter);
        if(selected.length > 0)
            listener.onItemsSelected(selected);

    }
    

    @Override
    public boolean performClick() {
        AlertDialog.Builder builder = new AlertDialog.Builder(getContext());
        Log.v("check it", ": " + items.size());
        Log.v("check it2", ": " + this.items.size());
        builder.setTitle(defaultText);
        Log.v("perform Click ::: ", " : check"+items.size());

        Log.v("perform Click ::: ", " : check2");
        builder.setMultiChoiceItems(
                items.toArray(new CharSequence[items.size()]),
                selected,
                this
        );
        builder.setPositiveButton(android.R.string.ok,
                new DialogInterface.OnClickListener() {

                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.cancel();
                    }
                });
        builder.setOnCancelListener(this);
        builder.show();
        return true;
    }

    public void setItems(List<String> items, String allText, int position,
                         MultiSpinnerListener listener) {
        this.items = items;
        this.defaultText = allText;
        this.listener = listener;
        Log.v("insetItems", ":");
        // all selected by default
        selected = new boolean[items.size()];
        for (int i = 0; i < selected.length; i++)
            selected[i] = false;

        // all text on the spinner
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(
                new CreateEntityActivity(),
                R.layout.textview_for_spinner,
                new String[] { allText }
        );
        setAdapter(adapter);

        if(position != -1)
        {
            selected[position] = true;
            listener.onItemsSelected(selected);

            onCancel(null);
        }

    }

    public interface MultiSpinnerListener {
        public void onItemsSelected(boolean[] selected);
    }
}`

**Comment by jssisodiya** [comment]
@pratikbutani ^^

**Comment by pratikbutani** [comment]
@jssisodiya Have you run my demo? Its working fine. 

May you want to do other thing with this.

**Comment by pratikbutani** [comment]
@jssisodiya Are you still getting this problem? If no, close this issue.
