### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by gaochuntie** [pratikbutani/MultiSelectSpinner#107]
While the system theme is dark,my application is light theme, the background of items is black.It's uncomfortable.
And after click a item,the dialog close,then a long black chunk wil be shown on the selectspinner ,it covers the spinner.Only by touching the screen can I hide the black chunk.
[https://t.me/+0Ouds6DUyhgwMDk1](url)
for ss

**Comment by pratikbutani** [comment]
Thank you @gaochuntie for finding this issue. I will be happy if you can fork & update the code accordingly. I am waiting for your update.

**Comment by gaochuntie** [comment]
Ok ,it's a little thing

**Comment by gaochuntie** [comment]
> Thank you @gaochuntie for finding this issue. I will be happy if you can fork & update the code accordingly. I am waiting for your update.

Sorry,I figured that it's appcompatspinner that causes the problem,I am lack in time to fix google's bugs
