### ISSUE TITLE
Need to Customize the background of "Choose Product" !

### ISSUE THREAD

**Issue by sans07** [pratikbutani/MultiSelectSpinner#11]
![screenshot_1479288002](https://cloud.githubusercontent.com/assets/23051788/20341378/019dbdf8-ac0c-11e6-92ba-45ea387e6ce6.png)

I need to know where i could change the background color behind the "Choose Product" on top of the view !

**Comment by pratikbutani** [comment]
You may have to see this for Custom Alert Dialog and you can change instead of Alert Dialog:

 [How can I change the color of AlertDialog title and the color of the line under it](http://stackoverflow.com/a/15285514/1318946)

**Comment by rpinto18** [comment]
@sans07  How to customize in that way?
