### ISSUE TITLE
I show popup view like multi popup in your demo.

### ISSUE THREAD

**Issue by sandip-chaniyara** [pratikbutani/MultiSelectSpinner#13]
I try to run your demo and getting one issue. when I click on spinner to view popup for selection It shows popup like **multi popup** view over there. I need _output like your screenshots_ you put for this demo.
I run app in **Samsung Galaxy S5(4.4.4)** and **Google Nexus 6(5.0)** devices in which I get this issue.
I attach my screenshot to show you the issue. please let me know the **solution of this issue** If you have any.
Thanks for your demo.
![untitled_new](https://cloud.githubusercontent.com/assets/4506295/20886835/f1a7e8d0-bb1d-11e6-8274-73d85f5c20fa.png)

**Comment by DionataFerraz** [comment]
In performClick add in builder.show;
builder.show().getWindow().setBackgroundDrawable(newColorDrawable(android.graphics.Color.TRANSPARENT));

**Comment by sushinpv** [comment]
In performClick() change the last lines as follows
        ad = builder.show();
        ad.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));
        return true;
