### ISSUE TITLE
How can I add this to my Android Studio project

### ISSUE THREAD

**Issue by fouadkada** [pratikbutani/MultiSelectSpinner#17]
usually android libraries can be easily added to android studio using gradle. However this library doesn't seem to have a way to be included using gradle nor does it have an example on how to add it manually.

can you please include any method of the above.

good work by the way :)

**Comment by pratikbutani** [comment]
Thank you for your appreciation. Currently I am working on that.  You may have to copy all the resources java and xml files for now.

Thank you.

**Comment by pratikbutani** [comment]
Now its available as dependency:

You can add following line to add as library.

`compile 'com.github.pratikbutani:MultiSelectSpinner:08d324c987'`
