### ISSUE TITLE
SingleSpinner Critical Problem

### ISSUE THREAD

**Issue by kitcat2014** [pratikbutani/MultiSelectSpinner#19]
hi

select an item 
then serach for other items
select new item

now in SingleSpinner you Select two Item

Check getSelectedItems

Please Fix This

and Have A question

How Can Set SpinnerText?
How Can Clear Selected Items?

Thanks

**Comment by ristodziuba** [comment]
Just add this line on the beginning of onClick method in OnClickListener in getView:
                    for (KeyPairBoolData item : items) item.setSelected(false);
This will clear selection from all items, not only filtered.
