### ISSUE TITLE
Error:(41, 13) Failed to resolve: com.github.pratikbutani:MultiSelectSpinner:c3051c6922 

### ISSUE THREAD

**Issue by kluz116** [pratikbutani/MultiSelectSpinner#21]

**Comment by josefrvaldes** [comment]
The same here. With the last version of Android Studio, minSdkVersion 19 and compileSdkVersion 26.

**Comment by pratikbutani** [comment]
Use 
`compile 'com.github.pratikbutani:MultiSelectSpinner:08d324c987'`

It will helps you.
