### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by Eldho93** [pratikbutani/MultiSelectSpinner#22]
Getting a random Null pointer exception inside the library.
Posting the error logs here. Please check

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
>        at com.androidbuts.multispinnerfilter.MultiSpinnerSearch.onCancel(Unknown Source)
>        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1339)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5551)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by pratikbutani** [comment]
I will check it out. 

Let me know if you find solution.

Thank you.
