### ISSUE TITLE
cannot resolve symbol MultiSpinnerSearchListener

### ISSUE THREAD

**Issue by shylendramadda** [pratikbutani/MultiSelectSpinner#23]
There is no class found for MultiSpinnerSearchListener. Is it MultiSpinnerSearch?

**Comment by pratikbutani** [comment]
Yes, you can check this code for more understanding.

[SpinnerListner](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/sample/src/main/java/com/androidbuts/sample/MainActivity.java#L85)

Thank you.
