### ISSUE TITLE
also add negative button and neutral button to the dialog box

### ISSUE THREAD

**Issue by 25Shubham96** [pratikbutani/MultiSelectSpinner#24]
can u add negative and neutral button to the dialog box in the same library or to a new build of same library

**Comment by pratikbutani** [comment]
Yes, Definitely.
Whenever I will get time to update. I will do forsure.

You can also contribute if you like it.

Thank you.

**Comment by 25Shubham96** [comment]
Please do not close this issue untill you update the library or after updating please reply on the same issue, I am waiting for the update...!!

**Comment by pratikbutani** [comment]
Please check the latest update.
