### ISSUE TITLE
Change spinner title

### ISSUE THREAD

**Issue by khaled-hayek** [pratikbutani/MultiSelectSpinner#25]
How can I change the title of the spinner from "select items" to what I need ??

**Comment by pratikbutani** [comment]
You can download whole zip of library and import in your project.

In [This class](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/library/src/main/java/com/androidbuts/multispinnerfilter/MultiSpinner.java#L80) you can edit title of Alert Dialog.

It will be static.

You can contribute that thing. Thank you.
