### ISSUE TITLE
when i add this to gradle, sync fails.

### ISSUE THREAD

**Issue by leenabhandari** [pratikbutani/MultiSelectSpinner#27]

**Comment by pratikbutani** [comment]
Have you checked #21 

I think that is same, may you get solution.

**Comment by Abhishekwayindia** [comment]
Failed to resolve: com.github.pratikbutani:MultiSelectSpinner:08d324c987

**Comment by carlosfelipetorres** [comment]
Still fails :/

**Comment by pratikbutani** [comment]
You can download whole library and add as a module in your project. That will work.
