### ISSUE TITLE
Select first element

### ISSUE THREAD

**Issue by rpinto18** [pratikbutani/MultiSelectSpinner#28]
Select the first item automatically? 

![screenshot_20180928-115254_gomapp 1](https://user-images.githubusercontent.com/11068934/46222212-36727380-c315-11e8-84fa-8f093839c93f.jpg)

**Comment by jerrymani33** [comment]
im come here by hacktoberfest what shud do here, i need to fix this issue or what ? any guidance plz

**Comment by pratikbutani** [comment]
Yeah you can fix the issue if you can or you can try our this [repo.](https://github.com/techieshubs/Men-GitHubers)
