### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by vivek50** [pratikbutani/MultiSelectSpinner#29]
Failed to resolve: com.github.pratikbutani:MultiSelectSpinner:08d324c987
After i put below line, in gradle file
`implementation 'com.github.pratikbutani:MultiSelectSpinner:08d324c987'`

**Comment by Monikasultania** [comment]
See this [https://github.com/pratikbutani/MultiSelectSpinner/issues/27#issuecomment-419639726](url)

**Comment by pratikbutani** [comment]
Check with this `implementation 'com.github.pratikbutani:MultiSelectSpinner:08d324c98'`
