### ISSUE TITLE
How can I Add My Custom List To The Spinner Which I Am Getting From Server

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [pratikbutani/MultiSelectSpinner#30]
final List<String> list = Arrays.asList(getResources().getStringArray(R.array.sports_array));

        final List<KeyPairBoolData> listArray = new ArrayList<KeyPairBoolData>();

        for (int i = 0; i < list.size(); i++) {
            KeyPairBoolData h = new KeyPairBoolData();
            h.setId(i + 1);
            h.setName(list.get(i));
            h.setSelected(false);
            listArray.add(h);
        }
        searchSpinner.setItems(listArray, -1, new SpinnerListener() {

            @Override
            public void onItemsSelected(List<KeyPairBoolData> items) {
                feeedback_question = new String[items.size()];
                int j = 0;
                for (int i = 0; i < items.size(); i++) {
                    if (items.get(i).isSelected()) {
                        feeedback_question[j] =items.get(i).getName();
                        Log.i("feedback", i + " : " + items.get(i).getName() + " : " + items.get(i).isSelected());
                        j++;
                    }
                }
            }
        });

**Comment by pratikbutani** [comment]
As I have created list here with for loop, you can bind array list from server data and pass it.
That's it.

**Comment by raiaslam** [comment]
listofuser = new ArrayList<>(Arrays.asList(listFoodModel.getUser()));
for(int i =0;i<alltouroperator.size();i++)
                        {
                            KeyPairBoolData h = new KeyPairBoolData();
                            l = Long.parseLong(alltouroperator.get(i).getId());
                            h.setId(l);
                            h.setName(alltouroperator.get(i).getName());
                             h.setSelected(false);
                                listArray0.add(h);
                            }


                        }
