### ISSUE TITLE
list looks very bad and to dialog box is appears

### ISSUE THREAD

**Issue by jitesh68** [pratikbutani/MultiSelectSpinner#32]
![whatsapp image 2018-12-06 at 12 34 16 pm](https://user-images.githubusercontent.com/22452777/49567294-492ba900-f953-11e8-9ec9-cf4afa53a51a.jpeg)

 
  List<KeyPairBoolData> listArray0 = new ArrayList<>();

//for server response
for(int i=0;i<servicesResponse.getData().size();i++){
                           // serviceList.add(servicesResponse.getData().get(i).getName());
                            KeyPairBoolData h = new KeyPairBoolData();
                            h.setId(i + 1);
                            h.setName(servicesResponse.getData().get(i).getName());
                            h.setSelected(false);
                            listArray0.add(h);
                        }

multiSelectSpinner.setItems(listArray0,  -1, new SpinnerListener() {
            @Override
            public void onItemsSelected(List<KeyPairBoolData> list) {
                for (int i = 0; i < list.size(); i++) {
                    if (list.get(i).isSelected()) {
                        Log.i("SELECTED", i + " : " + list.get(i).getName() + " : " + list.get(i).isSelected());
                    }
                }
            }

        });

**Comment by BismeetSingh** [comment]
Same problem.  Did  u find a solution

**Comment by pratikbutani** [comment]
The color combination and dialog view is changed now. Please check update.
