### ISSUE TITLE
How to get all selected items from the spinner and store it to an array list ?

### ISSUE THREAD

**Issue by HussainAbdulMajeed** [pratikbutani/MultiSelectSpinner#33]
I'm having a problem where i need to save all the clicked items of the spinner multi-list and store them in an array list. This list should only add the checked items and remove if there is an item that was previously checked and then unchecked. Any solutions?.....Thanks.

**Comment by pratikbutani** [comment]
The solution is given in the latest repo. You will get all the selected items in the listener instead of all items.
