### ISSUE TITLE
HintText not changing

### ISSUE THREAD

**Issue by tintinscorpion** [pratikbutani/MultiSelectSpinner#36]
app:hintText is not working. 
I found out the code doesnot detect the hinttext provided in xml and it only takes the default value assigned that is "Select Items".
Please look to this issue.

**Comment by Anca07** [comment]
I would like to work on this issue :)

**Comment by pratikbutani** [comment]
Can you post your code? or Please check the latest update.

    app:hintText="Multi Selection Spinner"

It's working for me.

If you still find the issue, post the new issue.
