### ISSUE TITLE
setSelection is not working

### ISSUE THREAD

**Issue by AyeshaFazal** [pratikbutani/MultiSelectSpinner#37]
How to pre-fill the MultiSearchSpinner with data from drop down

**Comment by nicemak** [comment]
Hi, did you find any solution?

**Comment by cr7rahul** [comment]
> How to pre-fill the MultiSearchSpinner with data from drop down

Got any solution forit?

**Comment by pratikbutani** [comment]
As per the following code, I got selected all the items.

    final List<KeyPairBoolData> listArray1 = new ArrayList<>();
    for (int i = 0; i < list.size(); i++) {
	    KeyPairBoolData h = new KeyPairBoolData();
	    h.setId(i + 1);
	    h.setName(list.get(i));
	    h.setSelected(true);
	    listArray1.add(h);
    }   

Please check this and do let me know if you get problem further. Hope you have updated the library.

**Comment by pratikbutani** [comment]
Open it again if you get a problem. Until I am closing this issue. Thank you.

**Comment by Rja-123** [comment]
After selection of any item the checkbox is not checked in set selection condition
