### ISSUE TITLE
Changing text of Filter Hint "Type Search" and text of "Not Found"

### ISSUE THREAD

**Issue by ridvan90** [pratikbutani/MultiSelectSpinner#39]
Hi,my friend,
How can I change text of **Filter Hint** and  **Not Found** error text.

**Comment by pratikbutani** [comment]
@ridvan90 Check latest [commit](https://github.com/pratikbutani/MultiSelectSpinner/commit/3201b301b7d7a1236275de3eb79a992b888c2932) 

Its solved.
