### ISSUE TITLE
Not able to Use in this Spinner for Edit Data in Android Activity

### ISSUE THREAD

**Issue by reachjmlvp** [pratikbutani/MultiSelectSpinner#41]
Cant able to set the selected text again to the single search spinner when using custom adapter. Simply setSelection is not working

**Comment by chydee** [comment]
Hi, can I help with this?

**Comment by pratikbutani** [comment]
@chydee Go on.. Thank you.

**Comment by pratikbutani** [comment]
**setSelection(true)** will work for you. Please post your issue again, I am closing this because it's very old and I have updated the new code.
