### ISSUE TITLE
SELECT ALL does not fire any event

### ISSUE THREAD

**Issue by surhidamatya** [pratikbutani/MultiSelectSpinner#43]
SELECT ALL does not fire any event

**Comment by ReThak** [comment]
SELECT ALL is selecting all the list of record when u will click on OK you will find that all in spinner. just do check its working.

**Comment by CleatonPais** [comment]
On clicking select all it closes the spinner showing a blank spinner
On opening the spinner again all the options are check and after clicking on OK  selected items to show on the spinner

**Comment by swapnil-92** [comment]
> On clicking select all it closes the spinner showing a blank spinner
> On opening the spinner again all the options are check and after clicking on OK selected items to show on the spinner

Same here. I downloaded the code and added  `onCancel(dialog);` inside `builder.setNeutralButton` and now all the names are added to spinner.

**Comment by pratikbutani** [comment]
Please check it now. Thank you.
