### ISSUE TITLE
when I search and select option is not filter

### ISSUE THREAD

**Issue by sharawanan** [pratikbutani/MultiSelectSpinner#49]
when I search and select option is not filter and at the same time two selection is display in single selection with filter

**Comment by sharawanan** [comment]
![video_2019-11-08_16-24-09](https://user-images.githubusercontent.com/34931626/68471526-6abca100-0244-11ea-81ff-7aced903eb18.gif)

**Comment by sharawanan** [comment]
please clear this issue

**Comment by pratikbutani** [comment]
Can you please check it now with an updated code. Do let me know if you find the issue again.
