### ISSUE TITLE
If i get selected items values  from server then how to show on spinner and then user update their items also. How is it possible?

### ISSUE THREAD

**Issue by Mayank1904** [pratikbutani/MultiSelectSpinner#5]

**Comment by iffanmajid** [comment]
Same question, how to set pre selected item

**Comment by bajaj1989** [comment]
Same question here. ? Did anyone get a solution?

**Comment by pratikbutani** [comment]
@Mayank1904  @iffanmajid @bajaj1989  You have bind that data same as we are binding static data.

**Comment by raiaslam** [comment]
i have two list one has all data and other has just selected item .then i filter and auto checked selected item that come from server ...................
see below example .......................................................................................................................................................
  /////////////////////////////Auto Checked list //////////////////////////////////////
                        workingwithtour = new ArrayList<>(listFoodModel.getTourGuideTourOperators());
  /////////////////////////////All  list //////////////////////////////////////
                        alltouroperator = new ArrayList<>(listFoodModel.getOperators());
///////////////////Loop that get data from list and compare ids and then set to spinner///////////
                        for(int i =0;i<alltouroperator.size();i++)
                        {
                            KeyPairBoolData h = new KeyPairBoolData();
                            l = Long.parseLong(alltouroperator.get(i).getId());
                            h.setId(l);
                            h.setName(alltouroperator.get(i).getName());
                            for(int j=0;j<workingwithtour.size();j++)
                            {
                                myid=workingwithtour.get(i).getTour_operator_id();
                                ll = Long.parseLong(myid);
                                if(l==ll)
                                {
                                     count=1;
                                    h.setSelected(true);
                                    listArray0.add(h);
                                }

                            }
                            if(count!=1)
                            {
                                h.setSelected(false);
                                listArray0.add(h);
                            }


                        }

**Comment by pratikbutani** [comment]
Please update and check,

You will get all the selected items in `onItemsSelected` as a list.

You can pass **setSelection(true)** for select item preselection.
