### ISSUE TITLE
How to change ok button text?

### ISSUE THREAD

**Issue by ytam** [pratikbutani/MultiSelectSpinner#50]
How to change ok button text? This button text change by changing divice language. But I want single text for all language.

**Comment by ysfm** [comment]
Import this project as library to your project

How to Import the library in Android Studio `https://github.com/MagicMicky/FreemiumLibrary/wiki/Import-the-library-in-Android-Studio`


Find your class in used your project.

For example i'm using MultiSpinnerSearch.class

on performClick 

You are create a AlertDialog. 


```
 builder.setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {

            @Override
            public void onClick(DialogInterface dialog, int which) {

                //Log.i(TAG, " ITEMS : " + items.size());
                dialog.cancel();
            }
 });
```

You can change your text in this line.
If u want hide a button, use this example.
`ad.getButton(AlertDialog.BUTTON_NEUTRAL).setVisibility(View.GONE);`

**Comment by pratikbutani** [comment]
It's not dynamic. If you want to change the text, download the library and change as you want.

Thank you.

I will add more dynamic feature soon.
