### ISSUE TITLE
Reseting the spinner

### ISSUE THREAD

**Issue by CleatonPais** [pratikbutani/MultiSelectSpinner#54]
I have set the limit of the multi spinner to 3 options. On selection of 3 options, it says limit exceeded which works perfectly.

I am trying to reset the spinner by using `listArray.clear()` which resets the options but not the selection. As a result, the spinner displays the option without selection but does not allow further selection 

Is there a method to reset the selection?

**Comment by karthi72** [comment]
I have fixed resetting the spinner value. I'm going to commit the change here u can check and revert back.

**Comment by karthi72** [comment]
I'm not having permission to commit,but u can change on your end by downloading the entire code and do changes in these places.

`In MultiSpinnerSearch class change **remove initialisation of selected object**`
`Add an extra parameter in setItems(List<KeyPairBoolData> items,int selection, int position, SpinnerListener listener)
{
this.selected=selection;
}`
This works for me :-)

**Comment by pratikbutani** [comment]
I have added "Clear All" button, You can use it.
