### ISSUE TITLE
Disable select all option in multi spinner

### ISSUE THREAD

**Issue by CleatonPais** [pratikbutani/MultiSelectSpinner#56]
This is my observation of the select all function for an already populated spinner
Prerequisite: loaded multi spinner,

Steps:
1)  Open the spinner. should display all the items in the spinner with checkboxes
2)  click on the select all option
3) This closes the spinner and should show the selected items on the spinner (it does not show the selection)
4)  On opening the spinner again, all the options are selected
5)  On clicking OK, the spinner closes and now show the selection

The selection should show on the first time rather than the second 

Also, the option of enabling and disabling the select all in the spinner would be great

Thanks

**Comment by skuodeveloper** [comment]
you should add codes below in MultiSpinnerSearch.java
ad.getButton( AlertDialog.BUTTON_NEUTRAL ).setOnClickListener( new OnClickListener() {
            @Override
            public void onClick(View v) {
                adapter.arrayList = adapter.mOriginalValues;
                for (int i = 0; i < adapter.mOriginalValues.size(); i++) {
                    adapter.arrayList.get( i ).setSelected( true );
                }
                adapter.notifyDataSetChanged();
            }
        } );

**Comment by pratikbutani** [comment]
https://github.com/pratikbutani/MultiSelectSpinner/issues/62
