### ISSUE TITLE
Change text size 

### ISSUE THREAD

**Issue by paularevalo** [pratikbutani/MultiSelectSpinner#6]
It is possible to change the text size of this component (when the dialog shows up). ?

**Comment by pratikbutani** [comment]
Yeah, You can change. [See this XML file](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/app/src/main/res/layout/textview_for_spinner.xml) In that you can specify your size.

**Comment by pixylife** [comment]
Is the text size option removed? I can't see any options

**Comment by pratikbutani** [comment]
You can download code and add the library to your project. You can change anything as per your requirement.

For textSize, you need to make a new row layout,
