### ISSUE TITLE
How to select multiple items in the spinner on creation

### ISSUE THREAD

**Issue by samuellim18** [pratikbutani/MultiSelectSpinner#60]
Hi, I was wondering if it is possible to pre-select multiple items and showing those selection on creation of the spinner. This for purposes such as updating user details after they have saved their selection on the registration page for example. Currently the position (default of -1 as below) only allows selection one item from the spinner.
```
searchSpinner.setItems(listArray, -1, new MultiSpinnerSearchListener() {
	@Override
	public void onItemsSelected(List<KeyPairBoolData> items) {

		for(int i=0; i<items.size(); i++) {
			if(items.get(i).isSelected()) {
				Log.i("TAG", i + " : " + items.get(i).getName() + " : " + items.get(i).isSelected());
			}
		}
	}
});
```

**Comment by pratikbutani** [comment]
Make such an item variable selected as `true` of your list array. It will automatically give you as selected when you pass it. 

Example: 

```
final List<KeyPairBoolData> listArray = new ArrayList<>();
for (int i = 0; i < list.size(); i++) {
	KeyPairBoolData h = new KeyPairBoolData();
	h.setId(i + 1);
	h.setName(list.get(i));
	h.setSelected(false); // Here you can pass true/false of each item.
	listArray.add(h);
}
```
