### ISSUE TITLE
hint text not displaying properly

### ISSUE THREAD

**Issue by amansoulace** [pratikbutani/MultiSelectSpinner#65]
value of hinttext is only shown when clicked on the multi spinner once. But i want to show the default text like "select items" or "select any" on creating the view.

**Comment by pratikbutani** [comment]
Have you checked?
 
   // A text that will display in search hint.
    multiSelectSpinnerWithSearch.setSearchHint("Select Any or Select Items");

**Comment by amansoulace** [comment]
![Screenshot_20200829-105129~2](https://user-images.githubusercontent.com/68734416/91629345-e2330b00-e9e5-11ea-87ba-b07c9bacf929.png)

Don't need hint for search, as, I'm using multi spinner without search. I want hint text for spinner, but it's showing blank, image attached for reference. Kindly provide a resolution.

**Comment by pratikbutani** [comment]
Write following line in your xml in tag of **MultiSelectSpinner**:

    app:hintText="Multi Item Selection"

**Comment by amansoulace** [comment]
Using below code to create multi spinner programmatically, but still hinttext is not displayed.
MultiSpinnerSearch multiSpinner = new MultiSpinnerSearch(this);
multiSpinner.setHintText("Select items");
multiSpinner.setSearchEnabled(false);

**Comment by pratikbutani** [comment]
@amansoulace  Please check it now.
