### ISSUE TITLE
Broken after latest version

### ISSUE THREAD

**Issue by OPunktSchmidt** [pratikbutani/MultiSelectSpinner#68]
Since today I get the following error when compiling my Android App. Is this a bug in the latest version?

```
C:\Development\AndroidFastCalorieCounter - GitHub\app\src\main\java\opunktschmidt\fastcaloriecounter\Ui\Dialogs\WeighReminderDialog.java:24: error: cannot find symbol
import com.androidbuts.multispinnerfilter.MultiSpinner;
                                         ^
  symbol:   class MultiSpinner
  location: package com.androidbuts.multispinnerfilter
```

**Comment by pratikbutani** [comment]
You can use MultiSelectSpinner,

The MultiSpinner is removed as it's unused because MultiSelectSpinner is
providing all possible things.

You just need to pass Key-Value array class.

Thank you.

**Comment by OPunktSchmidt** [comment]
Got it working again. Thank you. Btw, you're doing a great job!
