### ISSUE TITLE
Pre Select multiple items in MultiSearch Spinner

### ISSUE THREAD

**Issue by BuraqsysStudio** [pratikbutani/MultiSelectSpinner#69]
We can pre select single item in Single Item Spinner.
How to do it in Multi Search Spinner for multiple items.
Please Help.
Thanks

**Comment by pratikbutani** [comment]
#51 Please check this.

**Comment by pratikbutani** [comment]
Check the sample and see this [line](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/sample/src/main/java/com/androidbuts/sample/MainActivity.java#L52)

Just you need to pass **setSelection** as **true** 

Thank you.
