### ISSUE TITLE
Type parameter T has incompatible upper bounds: View and MultiSpinnerSearch

### ISSUE THREAD

**Issue by yaelvais** [pratikbutani/MultiSelectSpinner#71]
I have followed the instructions and imported, however I get the following error:
Type parameter T has incompatible upper bounds: View and MultiSpinnerSearch

For this line:
        MultiSpinnerSearch multiSelectSpinnerWithSearch = findViewById(R.id.multipleItemSelectionSpinner);

**Comment by pratikbutani** [comment]
Have you checked [example](https://github.com/pratikbutani/MultiSelectSpinner/tree/master/sample)?

**Comment by yaelvais** [comment]
Yes, Thank you it helped!
