### ISSUE TITLE
why Pressing BackButton calls onItemsSelected in SingleSpinnerSearch?

### ISSUE THREAD

**Issue by EngDjango** [pratikbutani/MultiSelectSpinner#72]
here is my full code:
````
posts_fab?.setOnClickListener {
            SingleSpinnerSearch(requireContext()).apply {
                setItems(items, object : SingleSpinnerListener {
                    override fun onItemsSelected(selectedItem: KeyPairBoolData?) {
                             // this is called every time the back button pressed
                    }
                    override fun onClear() {}
                })
                isColorseparation = true
                setEmptyTitle("Empty")
                setSearchHint("Select or Search")
                performClick()
            }
        }
````
and also how to not show the keyboard when the dialog shows?
thanks;

**Comment by pratikbutani** [comment]
Hello,

Because of this [line](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/library/src/main/java/com/androidbuts/multispinnerfilter/SingleSpinnerSearch.java#L200) you are getting this problem. 

If you can set it my yourself then it will be good otherwise I will update in next update.

Thank you.

**Comment by EngDjango** [comment]
@pratikbutani  thank you for your good work;
I'm about to publish the app so I'd appreciate it if you speed up the work;
also `how to stop the keyboard from showing when the dialog shows?`

**Comment by pratikbutani** [comment]
> @pratikbutani thank you for your good work;
> I'm about to publish the app so I'd appreciate it if you speed up the work;
> also `how to stop the keyboard from showing when the dialog shows?`

You can remove `searchView` , because of **SearchView** you are getting up that keyboard. Or If you want SearchView as it is then Write some code to hide keyboard after showing the dialog.

**Comment by EngDjango** [comment]
1- if the selected item is not null then I get some text in white color like in the picture below;
![Screenshot_20200910-082349](https://user-images.githubusercontent.com/16864903/92701953-e568b800-f350-11ea-872c-a07187b30619.jpg)
2- the text is single line! how to make it multiLine?
you should provide more customization options

**Comment by pratikbutani** [comment]
> 1- if the selected item is not null then I get some text in white color like in the picture below;
> ![Screenshot_20200910-082349](https://user-images.githubusercontent.com/16864903/92701953-e568b800-f350-11ea-872c-a07187b30619.jpg)
> 2- the text is single line! how to make it multiLine?
> you should provide more customization options

For Point - 1, It will be solved soon.
For Point - 2, You have to download the whole library and change the row layout of the adapter.

**Comment by pratikbutani** [comment]
@EngDjango Please check the updated library. Point - 1 issue solved.

**Comment by EngDjango** [comment]
@pratikbutani man I'm using the `object` parameter you removed from `KeyPairBoolData`
can you get it back?

> You have to download the whole library and change the row layout of the adapter

I don't know how to do this

**Comment by pratikbutani** [comment]
> KeyPairBoolData

Added Object Param.

**Comment by EngDjango** [comment]
@pratikbutani thank you;
can you plz provide options to override `android:singleLine="true"` in `item_listview_single.xml`
and `<requestFocus />` in `alert_dialog_listview_search.xml` ?

**Comment by pratikbutani** [comment]
It will be not useful to all, we need to think commonly. If you want to change anything in the layout then please download the project and add library folder in your project. It will be very helpful to you.
