### ISSUE TITLE
Clear all button should have dynamic text

### ISSUE THREAD

**Issue by pratikbutani** [pratikbutani/MultiSelectSpinner#75]
Currently, the MultiSelectSpinner has a "Clear all" button has a static string but it should have a dynamic. Users can set using methods.

**Comment by shakti97** [comment]
I would like to work on it @pratikbutani

**Comment by pratikbutani** [comment]
> I would like to work on it @pratikbutani

Do it

**Comment by pratikbutani** [comment]
https://github.com/pratikbutani/MultiSelectSpinner/pull/76
