### ISSUE TITLE
Styling of a multiSelectSpinnerWithSearch with setAdapter possible?

### ISSUE THREAD

**Issue by piet8stevens** [pratikbutani/MultiSelectSpinner#77]
Thank you for this MultiSelectSpinner - exactly what I was looking for in my app.

I added the following to your sample code:
```
       ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.spinner_item, list);
       multiSelectSpinnerWithSearch.setAdapter(adapter);
```
The applied styling from R.layout.spinner_item works when the spinner is shown the first time. But after using it once, the styling goes away and it returns to the same styling as without the adapter.

Any ideas? Or is there a better way to do this?

**Comment by pratikbutani** [comment]
If you have downloaded library and editing code in library itself, it will work definitely.

Have you tried same?

**Comment by piet8stevens** [comment]
Thank you for your rapid reply.

I am using the code by reference to your github, not by copying into my project. I  will try that tomorrow. So, can I just move the code to set the adapter in the multiSelectSpinnerWithSearch constructor?

**Comment by pratikbutani** [comment]
Yeah you can customise by your way. Do let me know if you have any
questions. 👍

**Comment by piet8stevens** [comment]
I have tried to include MultiSelectSpinnerWithSearch as a library into my project. I struggle - more to do with my own inexperience - in that I get an error message that ' attr/actionBarSize'  is defined twice in the generated file values.xm. I cannot find where the duplicate is generated from. I will work more on that today and report back on progress.

Thank you for your support.

**Comment by piet8stevens** [comment]
Thank you for your help. It is (almost) working.

**Comment by piet8stevens** [comment]
Well, I am afraid I closed it to soon. It worked last night. This morning, it stopped with this error: The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

When I checkout the commit before I added this as a library, I do not have this problem. Somehow last night, it did not show, but this morning as I was running tests on my own code, it appeared. I cannot find android.support.v4 anywhere in the code.

**Comment by pratikbutani** [comment]
The latest update is given for DataBinding only. Nothing changed more. Have you downloaded whole project or you are using dependency url.

**Comment by piet8stevens** [comment]
I have downloaded the whole project now and included as a library.

Interestingly enough, I just found out the app runs on a phone but this issue only happens when I run my tests (not androidTest, just regular junit test)

**Comment by piet8stevens** [comment]
I just got more info: it comes from Robolectric shadows. 
I upgraded to Android Studio 4.1 and now I get a more detailed error message.
Not sure why it does not show up when I do not use MultiSelectSpinner. 
I will try to solve and report back for the benefit of others.

**Comment by piet8stevens** [comment]
OK, If I comment out the robolectric:shadows-support form my build.gradle, it works.
I do not use shadows for now, so should be ok.
Thank you for your reactions.
