### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by SayalaGalvin** [pratikbutani/MultiSelectSpinner#80]
![image](https://user-images.githubusercontent.com/33367240/98435600-567ede80-20fa-11eb-9214-732bd652702e.png)

**Comment by pratikbutani** [comment]
Have you migrated your project to AndrodX?

**Comment by pratikbutani** [comment]
As you haven't replied I am going to close this issue for now.

Check [sample](https://github.com/pratikbutani/MultiSelectSpinner/blob/master/sample/build.gradle#L37)  and try again,

Feel free to open this issue again if you get a problem in the future.
