### ISSUE TITLE
Manifest merger failed : if sdk:minSdkVersion of project is < 19

### ISSUE THREAD

**Issue by tejpalb** [pratikbutani/MultiSelectSpinner#81]
Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [com.github.pratikbutani:MultiSelectSpinner:-SNAPSHOT] ....\jetified-MultiSelectSpinner--SNAPSHOT\AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.androidbuts.multispinnerfilter" to force usage (may lead to runtime failures)

Can you please update library "minSdkVersion" to 17?

to reproduce this issue change minSdkVersion version of project to 17 & rebuilt project

**Comment by pratikbutani** [comment]
Its not supports version 17, you need to update your minSdkVersion to 19.
