### ISSUE TITLE
Multiple MultiSelectSpinner in one activity

### ISSUE THREAD

**Issue by firdavsuo** [pratikbutani/MultiSelectSpinner#82]
There are multiple MultiSelectSpinners in one activity. If I select item of one MultiSelectSpinner then this item is also is selected on another MultiSelectSpinner. How can I do so that items of each MultiSelectSpinner were independent? Items of  each MultiSelectSpinner are separately declared.

**Comment by pratikbutani** [comment]
Just generate separate variables  for all the spinners. Its just an example for all Spinner Types in one activity but you can differentiate it by different variables.

Thanks

**Comment by firdavsuo** [comment]
Ok, thanks.
