### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by nirajbhatt22** [pratikbutani/MultiSelectSpinner#83]
![image](https://user-images.githubusercontent.com/17561434/107178013-547b3300-69fb-11eb-82c6-55474d160cf0.png)

**Comment by studentmanik** [comment]
same error here
"Failed to resolve: com.github.pratikbutani:MultiSelectSpinner:-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app"

**Comment by studentmanik** [comment]
> same error here
> "Failed to resolve: com.github.pratikbutani:MultiSelectSpinner:-SNAPSHOT
> Show in Project Structure dialog
> Affected Modules: app"

implementation 'com.github.pratikbutani:MultiSelectSpinner:f47c0dadea'
This one worked for me
