### ISSUE TITLE
Unable to clear selection programatically

### ISSUE THREAD

**Issue by MohanabalanD** [pratikbutani/MultiSelectSpinner#90]
I am trying to unselect all the selections and update the new list using the below code.
` 
        List<KeyPairBoolData> contentList = new ArrayList<>();
         KeyPairBoolData keyPairBoolData = new KeyPairBoolData("String", false);
         keyPairBoolData.setObject(stockZone);
         contentList.add(keyPairBoolData);

        multipleItemSelectionSpinner.setSearchEnabled(true);
        multipleItemSelectionSpinner.setSearchHint("Select  Items");
        multipleItemSelectionSpinner.setEmptyTitle("Not Data Found!");
        multipleItemSelectionSpinner.setClearText("Close & Clear");

        multipleItemSelectionSpinner.setItems(contentList, new MultiSpinnerListener() {
            @Override
            public void onItemsSelected(List<KeyPairBoolData> items) {
           }
        }
`

I have provided selection false for all items but still, selections are not getting cleared in the UI.
Any idea how to fix this issue?
Thanks in Advance

**Comment by MohanabalanD** [comment]
Modified Library by downloading it and adding it in the project

**Comment by pratikbutani** [comment]
> Modified Library by downloading it and adding it in the project

Thanks, Kindly post what you have changed to solve it or make PR.
